# Generated by Django 3.2.12 on 2023-05-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0004_auto_20230522_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketXpress.category'),
        ),
    ]
