# Generated by Django 3.2.12 on 2023-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0007_alter_customer_customer_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
