# Generated by Django 3.2.12 on 2023-05-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0012_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketXpress.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketXpress.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marketXpress.category'),
        ),
    ]
