# Generated by Django 3.2.12 on 2023-05-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0013_auto_20230522_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
