# Generated by Django 3.2.12 on 2023-05-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0015_customer_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ShippingAddress',
            new_name='shippingAddress',
        ),
    ]
