# Generated by Django 3.2.12 on 2023-05-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketXpress', '0016_rename_shippingaddress_customer_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
